//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heracles.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoleNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoleNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heracles.Web.Resources.RoleNames", typeof(RoleNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string MODULE_ADMIN {
            get {
                return ResourceManager.GetString("MODULE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string MODULE_CACHE {
            get {
                return ResourceManager.GetString("MODULE_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        public static string MODULE_CLEAR_CACHE {
            get {
                return ResourceManager.GetString("MODULE_CLEAR_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear settings.
        /// </summary>
        public static string MODULE_CLEAR_SETTINGS {
            get {
                return ResourceManager.GetString("MODULE_CLEAR_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dean.
        /// </summary>
        public static string MODULE_DEAN {
            get {
                return ResourceManager.GetString("MODULE_DEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string MODULE_DESKSBOOKS {
            get {
                return ResourceManager.GetString("MODULE_DESKSBOOKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string MODULE_DESKSEXAMS {
            get {
                return ResourceManager.GetString("MODULE_DESKSEXAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string MODULE_DESKSINDEX {
            get {
                return ResourceManager.GetString("MODULE_DESKSINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GramStax.
        /// </summary>
        public static string MODULE_GRAMSTAX {
            get {
                return ResourceManager.GetString("MODULE_GRAMSTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEC.
        /// </summary>
        public static string MODULE_PRODESKS {
            get {
                return ResourceManager.GetString("MODULE_PRODESKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string MODULE_TEACHER {
            get {
                return ResourceManager.GetString("MODULE_TEACHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermStax.
        /// </summary>
        public static string MODULE_TERMSTAX {
            get {
                return ResourceManager.GetString("MODULE_TERMSTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dean.
        /// </summary>
        public static string MODULE_USER_DEAN {
            get {
                return ResourceManager.GetString("MODULE_USER_DEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiseNet.
        /// </summary>
        public static string MODULE_WISENET {
            get {
                return ResourceManager.GetString("MODULE_WISENET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiseReader.
        /// </summary>
        public static string MODULE_WISEREADER {
            get {
                return ResourceManager.GetString("MODULE_WISEREADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiseTank.
        /// </summary>
        public static string MODULE_WISETANK {
            get {
                return ResourceManager.GetString("MODULE_WISETANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordStax.
        /// </summary>
        public static string MODULE_WORDSTAX {
            get {
                return ResourceManager.GetString("MODULE_WORDSTAX", resourceCulture);
            }
        }
    }
}
