//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heracles.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StackResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StackResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heracles.Web.Resources.StackResources", typeof(StackResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the correct translation.
        /// </summary>
        public static string Vocabulary1Statement {
            get {
                return ResourceManager.GetString("Vocabulary1Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the correct translation.
        /// </summary>
        public static string Vocabulary2Statement {
            get {
                return ResourceManager.GetString("Vocabulary2Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the word you hear.
        /// </summary>
        public static string Vocabulary3Statement {
            get {
                return ResourceManager.GetString("Vocabulary3Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the word you hear.
        /// </summary>
        public static string Vocabulary4Statement {
            get {
                return ResourceManager.GetString("Vocabulary4Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the right translation for each word.
        /// </summary>
        public static string Vocabulary5Statement {
            get {
                return ResourceManager.GetString("Vocabulary5Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the right word with its translation.
        /// </summary>
        public static string Vocabulary6Statement {
            get {
                return ResourceManager.GetString("Vocabulary6Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the most suitable word for each context.
        /// </summary>
        public static string Vocabulary7Statement {
            get {
                return ResourceManager.GetString("Vocabulary7Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No words.
        /// </summary>
        public static string VocabularyNoInboxData {
            get {
                return ResourceManager.GetString("VocabularyNoInboxData", resourceCulture);
            }
        }
    }
}
